[package]
name = "c_compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.61"
once_cell = "1.13.0"
thiserror = "1.0.32"
regex = "1.6.0"
